name : Test GitHub Action

run-name : Play by ${{ github.actor }}

on :
  schedule :
    - cron : "00 15 * * *" #UTC 기준 : 한국시간으로 5:00
  pull_request:


jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      # 워크플로우가 작동될 가상환경에 해당 레파지토리를 복사함
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
       
      #가상환경에 필요한 시스탬 종속성(?)
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install Python dependencies
      #파이썬 업데이트 및 필요한 모듈 설치
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #필요한지 확인해봐야함

      # - uses: mirromutth/mysql-action@v1.1
      #   with:
      #     host port: 3306
      #     container port: 3306
      #     mysql database: 'testdb'
      #     mysql root password: ${{ secrets.DB_PASSWORD }}