name : Test GitHub Action

run-name : Play by ${{ github.actor }}

#trigger 는 차후 변경될 수 있음
on :
  workflow_dispatch: # 수동으로 확인하기 위함
  schedule :
    - cron : "00 15 * * *" #UTC 기준 : 한국시간으로 5:00
  pull_request:


jobs:
  python-base-code: # python 기초 영역
    runs-on: ubuntu-latest

    steps:
      # 워크플로우가 작동될 가상환경에 해당 레파지토리를 복사함
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
       
      # 가상환경에 필요한 시스탬 종속성(?)
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev
      
      - name: Install Python dependencies
      # 파이썬 업데이트 및 필요한 모듈 설치
        run:  |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # sql 기본값 설정
      - name: Set up mysql connect
        run:  |
          echo '{"host":"'${{ secrets.MYSQL_ENDPOINT }}'","port":3306,"user":"'${{ secrets.MYSQL_USER }}'","password":"'${{ secrets.MYSQL_PASSWORD }}'"}' > ./mysql_info.json

      # sql index control    
      - name : Run test
        run : |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          python index_control_sql.py

  #-----------------------------#
  #병렬처리        
  python-work-code-{{index}}: # 실제로 돌아가는 부분
    needs: python-base-code
      # mysql 설치 및 태스트
      - name : Run test
        run : |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          python test_sql.py


